version: "3.8"

# WARNING! .install-modrinth.env must be created before running docker compose up
# It should contain the following variables:
# SERVER="/data/quilt-server-1.19.2-0.21.0-launcher.jar"
services:
  mc-server:
    container_name: mc-server
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    volumes:
      - ./server-data:/data

    environment:
      EULA: "TRUE"
      TYPE: MODRINTH
      VERSION: 1.19.2
      MEMORY: 4G
      DIFFICULTY: hard
      OPS: ${ADMIN}
      WHITELIST: ${ADMIN}
      MAX_TICK_TIME: -1
      RCON_PASSWORD: ${RCON_PASSWORD}
      MODRINTH_MODPACK: "UUATcpwj"
      MODRINTH_VERSION: "0.6.0"
      MODRINTH_LOADER: "quilt"
      MODS: |
        https://cdn.modrinth.com/data/6VdDUivB/versions/G1pSbE8U/essential_commands-0.33.2-mc1.19.2.jar
        https://cdn.modrinth.com/data/gF3BGWvG/versions/k5aItINr/open-parties-and-claims-fabric-1.19.2-0.20.0.jar
        https://cdn.modrinth.com/data/aZj58GfX/versions/ILLJbynj/easyauth-mc1.19.1-3.0.19.jar
        https://cdn.modrinth.com/data/LODybUe5/versions/1.0.1/easywhitelist-mc1.19-1.0.1.jar

  mc-backup:
    container_name: mc-backup
    image: itzg/mc-backup
    environment:
      RCON_HOST: mc-server
      RCON_PASSWORD: ${RCON_PASSWORD}
      BACKUP_METHOD: restic
      INITIAL_DELAY: 5m
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      RESTIC_REPOSITORY: ${RESTIC_REPOSITORY}
      # For S3
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      PRUNE_RESTIC_RETENTION: "--keep-daily 7 --keep-weekly 5"
    volumes:
      - ./server-data:/data:ro
