name = "The Adventurer's Journey"
author = "Conobi"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "791c4c5da1f74779f6281f78d4af75067be0df716953307eeedc0d0a4fc356ae"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2", "1.19.3", "1.19.4"]
datapack-folder = "datapacks"
