name = "The Adventurer's Journey"
author = "Conobi"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0448384c2bf71977c0614c2439b976314283890941c1d86ffb9e73265e2c157c"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2", "1.19.3", "1.19.4"]
datapack-folder = "datapacks"
