name = "The Adventurer's Journey"
author = "Conobi"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "089d00c2bb6cfca2901f893a9e1f7e3fef69a3b9d5ffd779db169058bc7f9dc8"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2", "1.19.3", "1.19.4"]
datapack-folder = "datapacks"
