name = "The Adventurer's Journey"
author = "Conobi"
version = "0.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f9562576aa39555c549519117c50c1c4cea50c67e011dd4aa4c55f4485a8b31"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2", "1.19.3", "1.19.4"]
datapack-folder = "datapacks"
