name: Setup repository | Workflow

on:
  create

jobs:
  disable-workflow:
    name: Disable this Workflow

    runs-on: ubuntu-latest

    if: github.event.ref == github.event.master_branch

    permissions:
      actions: write

    steps:
      - name: Disable this workflow
        shell: bash
        run: |
          gh workflow disable -R ${{ github.repository }} "${{ github.workflow }}"
        env:
          GITHUB_TOKEN: ${{ github.token }}

  initial-version:

    name: Set Inital Version

    permissions:
      contents: write

    if: github.event.ref == github.event.master_branch
    uses: ./.github/workflows/bump-version-release.yml
    with:
      release-tag: 0.1.0